# Generated by Django 2.2.4 on 2019-12-02 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Read')),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_joined', models.TimeField()),
                ('robot_type', models.CharField(max_length=50)),
                ('sensors', models.ManyToManyField(to='main.Sensor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='read',
            name='robot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Robot'),
        ),
        migrations.AddField(
            model_name='read',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sensor'),
        ),
        migrations.CreateModel(
            name='Past_movements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=30)),
                ('runtime_date', models.DateTimeField()),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Robot')),
            ],
        ),
        migrations.CreateModel(
            name='Current_movements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=30)),
                ('robot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Robot')),
            ],
        ),
    ]
