# Generated by Django 2.2.4 on 2019-12-02 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Current_movements',
            new_name='Current_movement',
        ),
        migrations.RenameModel(
            old_name='Past_movements',
            new_name='Past_movement',
        ),
    ]
