# Generated by Django 2.2.4 on 2019-12-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191202_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='date_joined',
            field=models.DateField(),
        ),
    ]
