# Generated by Django 2.2.4 on 2019-12-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191202_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
