# Generated by Django 2.2.4 on 2019-12-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20191202_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastmovement',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
