# Generated by Django 2.2.4 on 2019-12-05 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20191203_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='read',
            name='robot',
        ),
        migrations.RemoveField(
            model_name='read',
            name='sensor',
        ),
        migrations.AlterField(
            model_name='currentmovement',
            name='direction',
            field=models.CharField(choices=[('Right', 'Derecha'), ('Left', 'Izquierda'), ('Front', 'Avanzar'), ('Back', 'Retroceder'), ('Stop', 'Parar')], default='Front', max_length=30),
        ),
        migrations.AlterField(
            model_name='pastmovement',
            name='direction',
            field=models.CharField(choices=[('Right', 'Derecha'), ('Left', 'Izquierda'), ('Front', 'Avanzar'), ('Back', 'Retroceder'), ('Stop', 'Parar')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pastmovement',
            name='runtime_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='SensorInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Robot')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Sensor')),
            ],
        ),
        migrations.AddField(
            model_name='read',
            name='sensorinstance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.SensorInstance'),
        ),
    ]
