# Generated by Django 2.2.4 on 2019-12-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20191205_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='read',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
