# Generated by Django 2.2.4 on 2019-12-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20191205_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='image',
            field=models.ImageField(null=True, upload_to='images/sensors/'),
        ),
    ]
