# Generated by Django 2.2.4 on 2019-12-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_sensor_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robot',
            name='sensors',
        ),
        migrations.AddField(
            model_name='robot',
            name='image',
            field=models.ImageField(default='images/robots/defaultrobot.png', null=True, upload_to='images/robots'),
        ),
        migrations.AlterField(
            model_name='robot',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='image',
            field=models.ImageField(default='images/sensors/default.png', null=True, upload_to='images/sensors'),
        ),
    ]
