# Generated by Django 2.2.4 on 2019-12-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191206_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='read',
            name='field1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='read',
            name='field2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='read',
            name='field3',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
